import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '@/pages/about/Styles.module.less';
import { useRouter } from 'next/router';

const Detail: NextPage =()=>{
    const router = useRouter();
    const { id, pid} = router.query;
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App Home Detail!</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>hello world {id}Detail!{pid}</div>
        </div>
    )
};

export default Detail;