import type { NextPage } from 'next';
import Head from 'next/head';

const Blog: NextPage =()=>{
    return (
        <div>
            <Head>
                <title>Create Next App Blog Page!</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>hello world!</div>
        </div>
    )
};

// 此函数在构建时被调用
export async function getStaticProps() {
    // 调用外部 API 获取博文列表
    const res = await fetch('https://.../posts')
    const posts = await res.json()
  
    // 通过返回 { props: { posts } } 对象，Blog 组件
    // 在构建时将接收到 `posts` 参数
    return {
      props: {
        posts,
      },
    }
}


export default Blog;