import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Script from 'next/script';
import Navigation from '@/components/Navigation';

const logo = 'https://www.nextjs.cn/static/images/nextjs-logo.png';

const Home: NextPage =()=>{
    return (
        <div className='flex_center'>
            <Head>
                <title>Create Next App Home Page!</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <style data-href="https://fonts.googleapis.com/css2?family=Inter"></style>
            </Head>
            <div>
            <Navigation/>
               <h2>hello world!</h2> 
               <div>
                   <div>NODE_ENV:{process.env.NODE_ENV}</div>
                   {/* <div>PORT:{process.env.PORT}</div> */}
                   {/* <div>MYNAME:{process.env.MYNAME}</div>
                   <div>MYEMAIL:{process.env.MYEMAIL}</div> */}
                   <div>NEXT_PUBLIC_MYEMAIL:{process.env.NEXT_PUBLIC_MYEMAIL}</div>
               </div>
               <Image src={logo} alt='这是一张图片' className='img_style'  width={100} height={100} priority />
               {/* <Image 
                src={logo} 
                alt='这是一张图片'  
                layout='fill' 
                /> */}
            </div>
            <Script src="https://www.google-analytics.com/analytics.js" />
        </div>
    )
};

export default Home;